# Generated by Django 4.2.2 on 2023-06-16 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 16, 12, 35, 31, 165990, tzinfo=datetime.timezone.utc)),
        ),
    ]
