# Generated by Django 4.2.2 on 2023-06-16 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_alter_blog_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 16, 12, 36, 14, 544166, tzinfo=datetime.timezone.utc)),
        ),
    ]
