# Generated by Django 4.2.2 on 2023-07-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_contenttype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('link', 'link'), ('success', 'success'), ('black', 'black'), ('dark', 'dark'), ('light', 'light'), ('white', 'white'), ('warning', 'warning'), ('danger', 'danger')], default=('black', 'black'), max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
