# Generated by Django 4.2.2 on 2023-06-19 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_userprofile_alter_blog_author_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='author_of_blog', to='feed.userprofile'),
        ),
    ]
