# Generated by Django 4.2.2 on 2023-07-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_remove_userprofile_image_alter_contenttype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='feed/profile-pics/user-default.svg', upload_to='feed/profile-pics/', width_field='img_width'),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('success', 'success'), ('light', 'light'), ('warning', 'warning'), ('danger', 'danger')], default=('success', 'success'), max_length=20),
        ),
    ]
