# Generated by Django 4.2.2 on 2023-07-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0012_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='color',
            field=models.CharField(choices=[('prm', 'primary'), ('inf', 'info'), ('lnk', 'link'), ('suc', 'success'), ('blk', 'black'), ('drk', 'dark'), ('lgh', 'light'), ('wht', 'white'), ('wrn', 'warning'), ('dng', 'danger')], default=('lgh', 'light'), max_length=20),
        ),
    ]
