# Generated by Django 4.2.2 on 2023-07-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0013_contenttype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('link', 'link'), ('success', 'success'), ('black', 'black'), ('dark', 'dark'), ('light', 'light'), ('white', 'white'), ('warning', 'warning'), ('danger', 'danger')], default=('info', 'info'), max_length=20),
        ),
    ]
