# Generated by Django 4.2.2 on 2023-08-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_contenttype_color_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date'], 'permissions': (('can_create_blog', 'can create a blog'),)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-post_date'], 'permissions': (('can_create_comment', 'can add a comment'),)},
        ),
    ]
