# Generated by Django 4.2.2 on 2023-07-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0017_userprofile_followers_alter_contenttype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttype',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('link', 'link'), ('success', 'success'), ('black', 'black'), ('dark', 'dark'), ('light', 'light'), ('white', 'white'), ('warning', 'warning'), ('danger', 'danger')], default=('dark', 'dark'), max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
