# Generated by Django 4.2.2 on 2023-08-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_remove_userprofile_image_userprofile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(default='feed/blog-pics/white-bg.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(choices=[('AF', 'Afrikanns'), ('SQ', 'Albanian'), ('AR', 'Arabic'), ('HY', 'Armenian'), ('EU', 'Basque'), ('BN', 'Bengali'), ('BG', 'Bulgarian'), ('CA', 'Catalan'), ('KM', 'Cambodian'), ('ZH', 'Chinese (Mandarin)'), ('HR', 'Croation'), ('CS', 'Czech'), ('DA', 'Danish'), ('NL', 'Dutch'), ('EN', 'English'), ('ET', 'Estonian'), ('FJ', 'Fiji'), ('FI', 'Finnish'), ('FR', 'French'), ('KA', 'Georgian'), ('DE', 'German'), ('EL', 'Greek'), ('GU', 'Gujarati'), ('HE', 'Hebrew'), ('HI', 'Hindi'), ('HU', 'Hungarian'), ('IS', 'Icelandic'), ('ID', 'Indonesian'), ('GA', 'Irish'), ('IT', 'Italian'), ('JA', 'Japanese'), ('JW', 'Javanese'), ('KO', 'Korean'), ('LA', 'Latin'), ('LV', 'Latvian'), ('LT', 'Lithuanian'), ('MK', 'Macedonian'), ('MS', 'Malay'), ('ML', 'Malayalam'), ('MT', 'Maltese'), ('MI', 'Maori'), ('MR', 'Marathi'), ('MN', 'Mongolian'), ('NE', 'Nepali'), ('NO', 'Norwegian'), ('FA', 'Persian'), ('PL', 'Polish'), ('PT', 'Portuguese'), ('PA', 'Punjabi'), ('QU', 'Quechua'), ('RO', 'Romanian'), ('RU', 'Russian'), ('SM', 'Samoan'), ('SR', 'Serbian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('ES', 'Spanish'), ('SW', 'Swahili'), ('SV', 'Swedish '), ('TA', 'Tamil'), ('TT', 'Tatar'), ('TE', 'Telugu'), ('TH', 'Thai'), ('BO', 'Tibetan'), ('TO', 'Tonga'), ('TR', 'Turkish'), ('UK', 'Ukranian'), ('UR', 'Urdu'), ('UZ', 'Uzbek'), ('VI', 'Vietnamese'), ('CY', 'Welsh'), ('XH', 'Xhosa')], default='EN', max_length=50),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('success', 'success'), ('light', 'light'), ('warning', 'warning'), ('danger', 'danger')], default=('danger', 'danger'), max_length=20),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
