# Generated by Django 4.2.2 on 2023-08-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0019_blog_picture_alter_blog_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, default='feed/blog-pics/white-bg.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='contenttype',
            name='color',
            field=models.CharField(choices=[('primary', 'primary'), ('info', 'info'), ('success', 'success'), ('light', 'light'), ('warning', 'warning'), ('danger', 'danger')], default=('success', 'success'), max_length=20),
        ),
    ]
